version: '3'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - spring-boot-rest-mysql-network
    environment:
      - MYSQL_PASSWORD=9109
      - MYSQL_ROOT_PASSWORD=9109
      - MYSQL_DATABASE=alcoholmarket
    ports:
      - 3310:3306
    container_name: 'mysqldb'

  app:
    image: alcomarket
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - spring-boot-rest-mysql-network
    restart: on-failure
    ports:
      - 8085:8085
    environment:
      - DATABASE_USER=root
      - DATABASE_PASSWORD=9109
      - DATABASE_URL=jdbc:mysql://db:3306/alcoholmarket?useUnicode=true&serverTimezone=UTC&useSSL=true&verifyServerCertificate=false

networks:
  spring-boot-rest-mysql-network:
    driver: bridge





